apiVersion: 1

# Prometheus datasource provisioning
# Set the URL to the Prometheus service name in docker-compose

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
