name: CI/CD Pipeline


# Löst den Workflow bei Push oder Pull Request zum main-Branch ODER bei jedem Tag aus
on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Führt die Go-Tests aus
  test:
    runs-on: ubuntu-latest
    steps:
      # Schritt 1: Code aus dem Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v4

      # Schritt 2: Go-Umgebung einrichten
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Schritt 3: Go-Module-Cache
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Schritt 4: Abhängigkeiten laden
      - name: Tidy and download dependencies
        run: go mod tidy

      # Schritt 5: Unit-Tests mit Coverage ausführen
      - name: Run unit tests with coverage
        run: go test -v -cover ./...

  # Job 2: Baut das Docker-Image und lädt es hoch
  build-and-push:
    # Dieser Job läuft bei jedem Tag oder main-Push
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
